import java.util.Random;
import java.util.Scanner;

public class GuessTheNumber {
	Random r = new Random();
	int number = 0;
	int count = 0;
	public static void main(String[] args) {
		new GuessTheNumber();
	}
	
	public GuessTheNumber() {
		number = r.nextInt(100) + 1;
		while (loop());
	}
	
	public boolean endLoop(int guess, int number) {
		count += 1;
		if (guess == number) {
			System.out.println("You got it! It took you " + count + " guesses!");
			return false;
		} else {
			return true;
		}
	}
	
	public boolean loop() {
		int guess = 0;
		//BONUS: What strategy will beat this game the best?
		//Use the variable "number" for the number generated by the program
		//Use the varibale "guess" above
		/* Enter code below */
		
		
		System.out.println("Generated number: " + number); //Remove this when done

		/* You code should stop here */
		
		//When guess and number are the same this ends.
		return endLoop(guess, number);
	}
}
